"""
Re-verification of questions that were stored before verification existed.

The 37 variants generated by the old pipeline have no brute-force solution and
no input generator, so they cannot be trusted (some have test cases that
contradict their own problem statement). Rather than throwing them away:

1. The LLM writes ONLY the two missing helper programs (cheap - one small call,
   not a regeneration).
2. The question then goes through exactly the same checks as a new one.
3. Passing questions get ground-truth test outputs, a verification report and
   join the pool. Failing ones are marked "rejected" so they are never served.

The pass/fail counts here are also the honest "how bad was the old pipeline?"
number for the project report.
"""

import asyncio
import logging
from datetime import datetime, timezone
from typing import Optional

from app.clients.openai_client import get_openai_client
from app.clients.supabase_client import get_supabase_client
from app.services.verification import python_code, verify_variant

logger = logging.getLogger(__name__)

_lock = asyncio.Lock()
_progress: dict = {"running": False, "checked": 0, "passed": 0, "rejected": 0, "results": []}

VARIANT_FIELDS = (
    "title", "problem_statement", "test_cases", "solution_code",
    "stdin_wrappers", "function_template",
)


def progress() -> dict:
    """Progress of the current/last re-verification run."""
    return {**_progress, "results": _progress["results"][-20:]}


def _to_variant(row: dict) -> dict:
    """Build the in-memory variant shape the verifier expects from a DB row."""
    generator_field = row.get("test_generator_code") or {}
    if not isinstance(generator_field, dict):
        generator_field = {}
    variant = {field: row.get(field) for field in VARIANT_FIELDS}
    variant["brute_force_solution"] = {"python": generator_field.get("brute_force_python")}
    variant["test_generator_code"] = {"python": generator_field.get("python")}
    return variant


async def reverify_variant(row: dict, use_llm: bool = True,
                           force_helpers: bool = False) -> dict:
    """
    Re-verify one stored variant and write the result back.

    `force_helpers` throws away the stored oracle and has it rewritten from the
    problem statement alone — use it when the stored oracle can't be trusted
    (e.g. it was written while the reference solution was visible).
    """
    db = get_supabase_client()
    variant = _to_variant(row)
    title = (row.get("title") or "")[:45]

    stored = row.get("test_generator_code") if isinstance(row.get("test_generator_code"), dict) else {}
    previous_report = (stored or {}).get("verification_report") or {}
    # Helpers from a previous failed run are suspect (e.g. a brute force that was
    # too slow), so write fresh ones instead of failing the same way again.
    previous_failed = bool(previous_report) and not previous_report.get("passed", False)
    missing_helpers = (
        not python_code(variant["brute_force_solution"])
        or not python_code(variant["test_generator_code"])
    )

    # Step 1: write the helper programs when missing, unusable, or forced
    if missing_helpers or previous_failed or force_helpers:
        if not use_llm:
            return {"id": row["id"], "title": title, "status": "skipped",
                    "reason": "needs helper programs and use_llm=false"}
        why = "missing" if missing_helpers else ("forced" if force_helpers else "previous attempt failed")
        logger.info(f"[REVERIFY] Writing helpers for \"{title}\" ({why})...")
        helpers = await get_openai_client().write_verification_helpers(variant)
        if not helpers:
            return {"id": row["id"], "title": title, "status": "error",
                    "reason": "could not write brute force / generator"}
        variant.update(helpers)

    # Step 2: the same checks a new question must pass
    outcome = await verify_variant(variant)

    generator_field = {
        "python": python_code(variant.get("test_generator_code")),
        "brute_force_python": python_code(variant.get("brute_force_solution")),
        "verification_report": outcome.report or {
            "version": 1,
            "verified_at": datetime.now(timezone.utc).isoformat(),
            "passed": False,
            "failures": [
                {k: str(v)[:200] for k, v in f.items()} for f in outcome.failures[:5]
            ],
        },
    }

    if outcome.success:
        db.update_variant(row["id"], {
            # Ground-truth outputs replace whatever the old pipeline guessed
            "test_cases": outcome.variant["test_cases"],
            "test_generator_code": generator_field,
            "validation_status": "validated",
            "last_validated_at": datetime.now(timezone.utc).isoformat(),
        })
        logger.info(f"[REVERIFY] ✓ \"{title}\" passed — now in the pool")
        return {"id": row["id"], "title": title, "status": "passed",
                "report": outcome.report}

    kinds = sorted({f.get("kind", "?") for f in outcome.failures})
    db.update_variant(row["id"], {
        "test_generator_code": generator_field,
        "validation_status": "rejected",
        "last_validated_at": datetime.now(timezone.utc).isoformat(),
    })
    logger.warning(f"[REVERIFY] ✗ \"{title}\" rejected: {kinds}")
    return {"id": row["id"], "title": title, "status": "rejected", "failures": kinds}


async def reverify_all(limit: int = 50, use_llm: bool = True,
                       only_unverified: bool = True,
                       force_helpers: bool = False) -> dict:
    """Re-verify stored variants one at a time (LLM + PISTON are shared resources)."""
    if _lock.locked():
        return {"skipped": "a re-verification run is already in progress", **progress()}

    async with _lock:
        db = get_supabase_client()
        rows = db.get_variants(limit=200)
        if only_unverified:
            rows = [
                r for r in rows
                if not (isinstance(r.get("test_generator_code"), dict)
                        and (r["test_generator_code"] or {}).get("verification_report"))
            ]
        rows = rows[:limit]

        _progress.update({"running": True, "checked": 0, "passed": 0, "rejected": 0,
                          "results": [], "total": len(rows)})
        logger.info(f"[REVERIFY] Starting on {len(rows)} variant(s)")

        try:
            for row in rows:
                try:
                    result = await reverify_variant(row, use_llm=use_llm,
                                                    force_helpers=force_helpers)
                except Exception as e:
                    logger.error(f"[REVERIFY] Error on {row.get('id')}: {e}")
                    result = {"id": row.get("id"), "title": (row.get("title") or "")[:45],
                              "status": "error", "reason": str(e)[:150]}
                _progress["checked"] += 1
                if result["status"] == "passed":
                    _progress["passed"] += 1
                elif result["status"] == "rejected":
                    _progress["rejected"] += 1
                _progress["results"].append(result)
        finally:
            _progress["running"] = False

        logger.info(
            f"[REVERIFY] Done: {_progress['passed']} passed, {_progress['rejected']} rejected, "
            f"{_progress['checked']} checked"
        )
        return progress()
